spring:
  application:
    name: TestCaseManagement
  data:
    mongodb:
      uri: ${MONGODB_URL}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      auto-index-creation: true

springdoc:
  swagger-ui:
    path: /docs.html